server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    pipeline_stages:
      - json:
          expressions:
            service: service_name

      - labels:
          service:

    relabel_configs:
      # container id -> service_instance_id
      - source_labels: [ '__meta_docker_container_id' ]
        target_label: 'service_instance_id'
        regex: '^(.{12}).*'
        replacement: '$1'

      # container name -> instance
      - source_labels: ['__meta_docker_container_name']
        target_label: 'instance'
        regex: '/(.*)'
        replacement: '$1'

      # compose service -> compose_service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
        action: replace

      # If compose label is missing, fall back to container name
      - source_labels: ['compose_service','__meta_docker_container_name']
        target_label: 'compose_service'
        regex: '^$;/(.*)'
        replacement: '$1'
        action: replace

      # Optional: keep only containers with logging=promtail label
      - source_labels: ['__meta_docker_container_label_logging']
        regex: 'promtail'
        action: keep

      # Stream bilgisini (stdout/stderr) al
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'