server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
#      - host: ${DOCKER_HOST}
      - host: tcp://docker-socket-proxy-node:2375
        refresh_interval: 10s
    relabel_configs:
      # --- KEEP only containers explicitly labeled logging=promtail ---
      - source_labels: [__meta_docker_container_label_logging]
        regex: promtail
        action: keep

      # --- service name from swarm label ---
      - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: service
        action: replace

      # --- (optional) stack namespace ---
      - source_labels: [__meta_docker_container_label_com_docker_stack_namespace]
        target_label: stack
        action: replace

      # --- instance (container name without leading /) ---
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
        replacement: '$1'
        action: replace

      - source_labels: [__meta_docker_container_label_com_docker_swarm_task_id]
        target_label: service_instance_id
        action: replace

      - source_labels: [service_instance_id, __meta_docker_container_id]
        separator: ';'
        regex: '^$;(.{12}).*'
        target_label: service_instance_id
        replacement: '$1'
        action: replace

      # --- CRITICAL: tell promtail where container json logs are ---
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log
        action: replace

    pipeline_stages:
      - json:
          expressions:
            log: log
      - output:
          source: log
